name: d2s
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_0
  - aiofiles=24.1.0=pyhd8ed1ab_0
  - aiosmtplib=2.0.2=pyhd8ed1ab_0
  - alembic=1.13.3=pyhd8ed1ab_0
  - amqp=5.2.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_0
  - anyio=4.6.2.post1=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h9ecbd09_5
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.7.31=hcdce11a_5
  - aws-c-cal=0.7.4=hd3f4568_4
  - aws-c-common=0.9.31=hb9d3cd8_0
  - aws-c-compression=0.2.19=hf20e7d7_4
  - aws-c-event-stream=0.5.0=h72d8268_0
  - aws-c-http=0.8.10=h6bb76cc_5
  - aws-c-io=0.14.20=h389d861_2
  - aws-c-mqtt=0.10.7=had056f2_5
  - aws-c-s3=0.7.0=hc85afc5_0
  - aws-c-sdkutils=0.1.19=hf20e7d7_6
  - aws-checksums=0.1.20=hf20e7d7_3
  - aws-crt-cpp=0.29.0=h07ed512_0
  - aws-sdk-cpp=1.11.407=h9c41b47_6
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - backports.zoneinfo=0.2.1=py311h38be061_9
  - bcrypt=4.2.0=py311h9e33e62_1
  - billiard=4.2.1=py311h9ecbd09_0
  - black=24.10.0=py311h38be061_0
  - blinker=1.8.2=pyhd8ed1ab_0
  - blosc=1.21.6=hef167b5_0
  - boto3=1.35.49=pyhd8ed1ab_0
  - botocore=1.35.49=pyge310_1234567_0
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.2=heb4867d_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cairo=1.18.0=hebfffa5_3
  - celery=5.4.0=pyhd8ed1ab_1
  - ceres-solver=2.2.0=ha77e7a2_4
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - cfitsio=4.4.1=ha728647_2
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-didyoumean=0.3.1=pyhd8ed1ab_0
  - click-plugins=1.1.1=py_0
  - click-repl=0.3.0=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.3.0=py311hd18a35c_2
  - coverage=7.6.4=py311h2dc5d0c_0
  - cpd=0.5.5=h434a139_2
  - cryptography=43.0.3=py311hafd3f86_0
  - curl=8.10.1=hbbe4b11_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dnspython=2.7.0=pyhff2d567_0
  - draco=1.5.7=h00ab1b0_0
  - ecdsa=0.19.0=pyhd8ed1ab_0
  - eigen=3.4.0=h00ab1b0_0
  - email-validator=2.2.0=pyhd8ed1ab_0
  - email_validator=2.2.0=hd8ed1ab_0
  - entwine=2.2.0=hb071377_4
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - expat=2.6.3=h5888daf_0
  - faker=30.8.1=pyhd8ed1ab_0
  - fastapi=0.115.4=pyhd8ed1ab_0
  - fastapi-cli=0.0.5=pyhd8ed1ab_1
  - fastapi-mail=1.4.1=pyhd8ed1ab_0
  - fgt=0.4.11=h87365c0_1
  - fiona=1.10.1=py311h35c0331_1
  - flake8=7.1.1=pyhd8ed1ab_0
  - flower=2.0.1=py311h38be061_1
  - fmt=11.0.2=h434a139_0
  - folium=0.18.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.54.1=py311h2dc5d0c_1
  - freetype=2.12.1=h267a509_2
  - freexl=2.0.0=h743c826_0
  - gdal=3.9.3=py311h5159542_0
  - geoalchemy2=0.15.2=pyhd8ed1ab_0
  - geojson-pydantic=1.1.2=pyh3cfb1c2_0
  - geopandas=1.0.1=pyhd8ed1ab_1
  - geopandas-base=1.0.1=pyha770c72_1
  - geos=3.13.0=h5888daf_0
  - geotiff=1.7.3=h77b800c_3
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py311h0f6cedb_2
  - greenlet=3.1.1=py311hfdbb021_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.6=pyhd8ed1ab_0
  - httptools=0.6.1=py311h9ecbd09_1
  - httpx=0.27.2=pyhd8ed1ab_0
  - humanize=4.11.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - isort=5.13.2=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - kealib=1.5.3=hf8d3e68_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - kombu=5.4.1=py311h38be061_0
  - krb5=1.21.3=h659f571_0
  - laspy=2.5.4=py311h781c19f_1
  - lazrs-python=0.6.2=py311h9e33e62_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240722.0=cxx17_h5888daf_1
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.4=hfca40fe_0
  - libarrow=16.1.0=ha5db6c2_36_cpu
  - libarrow-acero=16.1.0=h5888daf_36_cpu
  - libarrow-dataset=16.1.0=h5888daf_36_cpu
  - libblas=3.9.0=25_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=25_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.10.1=hbbe4b11_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgdal=3.9.3=ha770c72_0
  - libgdal-arrow-parquet=3.9.3=h7a91b6f_0
  - libgdal-core=3.9.3=hd5b9bfb_0
  - libgdal-fits=3.9.3=h2db6552_0
  - libgdal-grib=3.9.3=hc3b29a1_0
  - libgdal-hdf4=3.9.3=hd5ecb85_0
  - libgdal-hdf5=3.9.3=h6283f77_0
  - libgdal-jp2openjpeg=3.9.3=h1b2c38e_0
  - libgdal-kea=3.9.3=h1df15e4_0
  - libgdal-netcdf=3.9.3=hf2d2f32_0
  - libgdal-pdf=3.9.3=h600f43f_0
  - libgdal-pg=3.9.3=h5e77dd0_0
  - libgdal-postgisraster=3.9.3=h5e77dd0_0
  - libgdal-tiledb=3.9.3=h4a3bace_0
  - libgdal-xls=3.9.3=h03c987c_0
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.82.2=h2ff4ddf_0
  - libgomp=14.2.0=h77fa898_1
  - libgoogle-cloud=2.30.0=h438788a_0
  - libgoogle-cloud-storage=2.30.0=h0121fbd_0
  - libgrpc=1.65.5=hf5c653b_0
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=25_linux64_openblas
  - libnetcdf=4.9.2=nompi_h135f659_114
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.10.0=h4bc722e_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.4=h7f98852_1002
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libparquet=16.1.0=h6bd9018_36_cpu
  - libpdal=2.8.1=ha770c72_0
  - libpdal-arrow=2.8.1=hdc15099_0
  - libpdal-core=2.8.1=h8f62525_0
  - libpdal-cpd=2.8.1=h5888daf_0
  - libpdal-draco=2.8.1=h5888daf_0
  - libpdal-e57=2.8.1=h258f5e6_0
  - libpdal-hdf=2.8.1=hf8d3e68_0
  - libpdal-icebridge=2.8.1=hf8d3e68_0
  - libpdal-nitf=2.8.1=h86beebd_0
  - libpdal-pgpointcloud=2.8.1=ha2a7bca_0
  - libpdal-tiledb=2.8.1=h1afda8b_0
  - libpdal-trajectory=2.8.1=h8c7babf_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=17.0=h04577a9_4
  - libprotobuf=5.27.5=h5b01275_2
  - libre2-11=2024.07.02=hbbce691_1
  - librttopo=1.1.0=h97f6797_17
  - libspatialite=5.1.0=h1b4f908_11
  - libsqlite=3.47.0=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=he137b08_1
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.49.2=hb9d3cd8_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libxslt=1.1.39=h76b75d6_0
  - libzip=1.11.1=hf83b1b0_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - mako=1.3.5=pyhd8ed1ab_0
  - mapclassify=2.8.1=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py311h2dc5d0c_0
  - matplotlib-base=3.9.2=py311h2b939e6_1
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - metis=5.1.0=hd0bcaf9_1007
  - minizip=4.0.7=h401b404_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpi=1.0=openmpi
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy=1.13.0=py311h9ecbd09_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.5=he02047a_1
  - networkx=3.4.2=pyhd8ed1ab_0
  - nitro=2.7.dev8=h59595ed_0
  - nspr=4.36=h5888daf_0
  - nss=3.106=hdf54f9c_0
  - numpy=1.26.4=py311h64a7726_0
  - openjpeg=2.5.2=h488ebb8_0
  - openldap=2.6.8=hedd0468_0
  - openmpi=5.0.5=h9a79eee_101
  - openssl=3.3.2=hb9d3cd8_0
  - orc=2.0.2=h690cf93_1
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py311h7db5c69_1
  - passlib=1.7.4=pyhd8ed1ab_1
  - pathspec=0.12.1=pyhd8ed1ab_0
  - pcre2=10.44=hba22ea6_2
  - pdal=2.8.1=hd8ed1ab_0
  - pika=1.3.1=pyhd8ed1ab_0
  - pillow=11.0.0=py311h49e9ac3_0
  - pip=24.2=pyh8b19718_1
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - poppler=24.08.0=h47131b8_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=17.0=h1122569_4
  - proj=9.5.0=h12925eb_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_0
  - psutil=6.1.0=py311h9ecbd09_0
  - psycopg2=2.9.9=py311h83e8966_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyasn1=0.6.1=pyhd8ed1ab_1
  - pycodestyle=2.12.1=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=2.9.2=pyhd8ed1ab_0
  - pydantic-core=2.23.4=py311h9e33e62_0
  - pydantic-settings=2.6.0=pyh3cfb1c2_0
  - pyflakes=3.2.0=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyogrio=0.10.0=py311h5fbebbf_0
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pyproj=3.7.0=py311h0f98d5a_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.3.3=pyhd8ed1ab_0
  - pytest-cov=5.0.0=pyhd8ed1ab_0
  - python=3.11.10=hc5c86c4_3_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-dotenv=1.0.1=pyhd8ed1ab_0
  - python-jose=3.3.0=pyh6c4a22f_1
  - python-multipart=0.0.16=pyhff2d567_0
  - python-pdal=3.4.5=py311h870b839_12
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h9ecbd09_1
  - qhull=2020.2=h434a139_5
  - rasterio=1.4.1=py311hfbe26e2_0
  - rasterstats=0.20.0=pyhd8ed1ab_0
  - re2=2024.07.02=h77b4e00_1
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - rich=13.9.3=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - s2n=1.5.5=h3931f03_0
  - s3transfer=0.10.3=pyhd8ed1ab_0
  - scikit-learn=1.5.2=py311h57cc02b_1
  - scipy=1.14.1=py311he9a78e4_1
  - setuptools=75.1.0=pyhd8ed1ab_0
  - shapely=2.0.6=py311h2fdb869_2
  - shellingham=1.5.4=pyhd8ed1ab_0
  - simplejson=3.19.3=py311h9ecbd09_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=ha2e4443_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - snuggs=1.4.7=pyhd8ed1ab_1
  - spdlog=1.14.1=hed91bc2_1
  - sqlalchemy=2.0.36=py311h9ecbd09_0
  - sqlite=3.47.0=h9eae976_0
  - starlette=0.41.0=pyhd8ed1ab_0
  - suitesparse=7.8.2=hb42a789_0
  - tbb=2021.13.0=h84d6215_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tiledb=2.26.2=hd64914e_4
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - tornado=6.4.1=py311h9ecbd09_1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - typer=0.12.5=pyhd8ed1ab_0
  - typer-slim=0.12.5=pyhd8ed1ab_0
  - typer-slim-standard=0.12.5=hd8ed1ab_0
  - types-aiofiles=24.1.0.20240626=pyhd8ed1ab_0
  - types-psycopg2=2.9.21.20240819=pyhd8ed1ab_0
  - types-pyyaml=6.0.12.20240917=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzcode=2024b=hb9d3cd8_0
  - tzdata=2024b=hc8b5060_0
  - unicodedata2=15.1.0=py311h9ecbd09_1
  - untwine=1.3.2=hefcc2fe_2
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - uvicorn=0.32.0=py311h38be061_0
  - uvicorn-standard=0.32.0=h38be061_0
  - uvloop=0.21.0=py311h9ecbd09_0
  - vine=5.1.0=pyhd8ed1ab_0
  - watchfiles=0.24.0=py311h9e33e62_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - websockets=13.1=py311h9ecbd09_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xerces-c=3.2.5=h988505b_2
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_1
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xyzservices=2024.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py311hbc35293_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - pdal-plugins==1.6.2
